### ISSUE TITLE
Number problem

### ISSUE THREAD

**Issue by diegodfsd** [nilproject/NiL.JS#258]
We are using NiL.JS already have a significant time and in the last few days, we noticed a strange behavior when working with numbers.

We don't understand why the number 69.85 is transformed to 69.84999999999999 no matter if we type it explicitly or make a calc to result in this magic number the result is always the same.

This is a snippet to help to reproduce the error.

```
var context= new Context();
context.Eval("console.log(parseFloat('69.85'));", true);
```

Even using another approach the result is the same:
```
Func<decimal, int, string, decimal> round = (value, precision, roundingType) =>
{
    return System.Math.Round(value, precision, Enum.Parse<MidpointRounding>(roundingType, true));
};

var context= new Context();
context.DefineVariable("upTo").Assign(JSValue.Marshal(round));
context.Eval("console.log(upTo(69.84999999999999, 2, 'AwayFromZero'));", true);
```

About the environment:
.NET Core SDK 5.0.303
Nil.JS Version = 2.5.1466 and 2.5.1514

**Comment by nilproject** [comment]
So, on the first view, it is bug of "stringification", not parsing or something else. [This](https://github.com/nilproject/NiL.JS/blob/af2637e156564a731cb54ca5134cb38ec12362b5/NiL.JS/Core/Tools.cs#L821) function contains (at least) one dangerous action, that bring to this bug. I will fix it soon

**Comment by diegodfsd** [comment]
> So, on the first view, it is bug of "stringification", not parsing or something else. [This](https://github.com/nilproject/NiL.JS/blob/af2637e156564a731cb54ca5134cb38ec12362b5/NiL.JS/Core/Tools.cs#L821) function contains (at least) one dangerous action, that bring to this bug. I will fix it soon

@nilproject I'm working on a solution to fix this bug, wait for my PR ;)

**Comment by nilproject** [comment]
Fixed in #260

**Comment by diegodfsd** [comment]
@nilproject I'll need your help again because the problem is back. I found other cases, for example:
10.66999999999999, 20.98999999999999, 10.42999999999999, 20.98999999999999, and others. Do you have an idea to solve this?

About the environment:
.NET Core SDK 5.0.303
Nil.JS Version = 2.5.1466 and 2.5.1539

**Comment by nilproject** [comment]
Thanks! This happened because of two missing lines

**Comment by diegodfsd** [comment]
@nilproject after your last commit, I took some numbers to test over develop branch, and at least a case continues with unexpected behavior. The number 8.06 is converted to 8.060000000000001.
I just added the below cases in NumberUtilsTests.DoubleToString test

`new KeyValuePair<double, string>(20.99, "20.99"),
 new KeyValuePair<double, string>(10.19, "10.19"),
 new KeyValuePair<double, string>(8.06, "8.06"),
 new KeyValuePair<double, string>(10.36, "10.36"),
 new KeyValuePair<double, string>(0.56, "0.56"),
 new KeyValuePair<double, string>(0.68, "0.68"),
 new KeyValuePair<double, string>(9.12, "9.12")`

**Comment by nilproject** [comment]
@diegodfsd please, check my fix. I changed the logic of rounding

**Comment by diegodfsd** [comment]
@nilproject thanks! I saw you changed the algorithm and added another test cases and with I know until now seems enough to fix the problem. Do you believe that a new version can be released today?

**Comment by nilproject** [comment]
Just uploaded to nuget
